---
- name: Install Nginx | Installation Nginx
  hosts: lighthouse
  roles:
    - nginx-role
- name: Install lighthouse |Installation lighthouse
  hosts: lighthouse
  pre_tasks:
    - name: lighthouse | Install dependencis
      become: true
      ansible.builtin.yum:
        name: git
        state: present
  roles:
    - lighthouse-role   
- name: Install Clickhouse |Installation Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
- name: Install Vector | Installation vector
  hosts: vector
  roles:
    - vector-role
